---
- name: "add worker to swarm"
  docker_swarm:
    state: join
    advertise_addr: worker_ip
    join_token: "{{ hostvars['manager_ip']['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: [ 'manager_ip:2377' ]